name: service_route
description: Service RotasÄ±.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.0"
  firebase_crashlytics: ^0.2.1
  provider: ^4.3.2+2
  flutter_bloc: ^6.0.5
  clock: ^1.0.1
  dio: ^3.0.10
  sembast: ^2.4.7+7
  path_provider: ^1.6.18
  rxdart: ^0.24.1
  permission_handler: ^5.0.1+1
  aff:
    path: ../aff/
    # git:
    #   url: git://github.com/erkanmaras/aff.git
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  intl_translation: ^0.17.10+1


flutter:
  assets:
      - assets/images/
      
  # fonts:
  #   - family: OpenSans
  #     fonts: 
  #       - asset: assets/fonts/opensans/OpenSans-Bold.ttf
  #       ...
  #       ... 
  uses-material-design: true
 